add pyproject.toml and black, updated reqs
AnnaliseAI/pythonpackagecookie pull request #12
Opened 2021-04-07 06:39 UTC by xiahongze

bump version for some of the packages
add black
add pyproject.toml

2021-04-07 07:41 UTC, StephenHogg requested changes

2021-04-07 07:41 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/.vscode/settings.json
> -    "python.formatting.provider": "yapf",
I think we actually need to edit the cookiecutter to prompt the user to choose between yapf and black. Ben H's team use yapf at the moment, while the Optimus guys use black. This means that we would want to use black while others using this cookiecutter might want to use yapf. Seem reasonable?

2021-04-07 07:41 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/pylintrc
> +        missing-class-docstring,
Any reason we're ignoring the absence of docstrings?

2021-04-07 07:41 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/.vscode/settings.json
> -    "python.formatting.provider": "yapf",
Is it worth also updating the build scripts in the `scripts` directory to use black/yapf and isort so they become part of the build process always?

2021-04-07 07:41 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/setup.py
> +    'pytest>=6.2.0',
6.2.0 here but 6.2.1 in requirements.txt

2021-04-08 03:40 UTC, StephenHogg requested changes

2021-04-08 03:40 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/requirements.txt
> +{% if cookiecutter.formatter == 'black' %}black==20.8b1{% else %}yapf==0.29.0{% endif %}
add yapf to requirements.txt if it is requested?

2021-04-08 03:42 UTC, xiahongze commented on {{cookiecutter.project_slug}}/requirements.txt
> +{% if cookiecutter.formatter == 'black' %}black==20.8b1{% else %}yapf==0.29.0{% endif %}
i believe it is added???

2021-04-08 04:00 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/pylintrc
> +        missing-class-docstring,
Only this one left, and we're done

2021-04-08 04:28 UTC, xiahongze commented on {{cookiecutter.project_slug}}/pylintrc
> +        missing-class-docstring,
please note that there is an outdated icon in this thread, meaning that the code you looked is no longer there.

2021-04-08 04:51 UTC, StephenHogg commented on {{cookiecutter.project_slug}}/pylintrc
> +        missing-class-docstring,
Very sorry! I look up to your ability as a coder every day :)

2021-04-08 04:51 UTC, StephenHogg approved these changes

2021-04-08 04:52 UTC, StephenHogg commented
PR approved, thanks for this!

2021-04-08 04:54 UTC, merged